Fix/better picture storage
beatlink-epfl/beatlink pull request #146
Opened 2024-11-21 18:46 UTC by sandroquist

This pull request focuses on refactoring the profile picture handling in the `Profile` feature of the app. The changes include replacing the use of `Uri` for profile pictures with `Bitmap` and Base64 encoding for better performance and compatibility. Additionally, the profile picture upload and retrieval methods have been updated to support these changes.

### Profile Picture Handling Refactor:

* [`app/src/main/java/com/epfl/beatlink/model/profile/ProfileData.kt`](diffhunk://#diff-2a5ea1244ae6927bda2af58b5bafa711066a5019720722739ffaba0674f00803L22-R20): Changed the `profilePicture` field from `Uri?` to `String?` to store the Base64 encoded image.
* [`app/src/main/java/com/epfl/beatlink/repository/profile/ProfileRepositoryFirestore.kt`](diffhunk://#diff-4b084ab579838f2c552fa2f1943c2de3b8eeaae09c8e3794d6c0ba07de5e174bL18-R41): Updated methods to handle profile picture upload and retrieval using Base64 encoded images and `Bitmap`. Added methods to resize, compress, and convert images to Base64. 
* [`app/src/main/java/com/epfl/beatlink/model/profile/ProfileRepository.kt`](diffhunk://#diff-134f7b5873398c22b21cef7e1fd53339de9f483c340936d58584adb96a7d3fadL47-R66): Modified the `uploadProfilePicture` method to accept `Uri` and added a new method `loadProfilePicture` to load the profile picture as a `Bitmap`.

### UI Components Update:

* [`app/src/main/java/com/epfl/beatlink/ui/components/MainComponents.kt`](diffhunk://#diff-45cba655b191a59e9a8e13f3bcbc92a889c0ac0d7f6c17a815827d656ac4466dL551-R572): Updated the `ProfilePicture` composable to accept a `MutableState<Bitmap?>` instead of `Uri` and display the image accordingly.

### Profile Screen and Edit Profile Screen Update:

* [`app/src/main/java/com/epfl/beatlink/ui/profile/EditProfile.kt`](diffhunk://#diff-881a530c95fe57f2aac377e0fe4ef67c6c205810638b9a85c0566195257902ddL73-R90): Updated the `EditProfileScreen` to handle profile picture upload and display using `Bitmap`. Added logic to load and update the profile picture. 
* [`app/src/main/java/com/epfl/beatlink/ui/profile/Profile.kt`](diffhunk://#diff-c005ae949d47d51bc56ac642e1a5444a7a4443f7c157bc2ccce32f0feec9c2efR70-R73): Updated the `ProfileScreen` to load and display the profile picture using `Bitmap`.

These changes improve the handling of profile pictures by using more efficient image processing techniques and ensure compatibility across different parts of the application.

2024-11-21 23:48 UTC, lunasrc requested changes
Great work on this pull request! The changes bring significant improvements to how profile pictures are handled in the app. You're almost there to get this approved — just a few minor adjustments to refine the implementation!

2024-11-21 23:48 UTC, lunasrc commented on app/src/main/java/com/epfl/beatlink/repository/profile/ProfileRepositoryFirestore.kt
There are two variables with the same definition.

2024-11-21 23:48 UTC, lunasrc commented on app/src/main/java/com/epfl/beatlink/repository/profile/ProfileRepositoryFirestore.kt
> +      val profilePicture = snapshot.getString("profilePicture")
Instead of creating a new variable, you can directly add this initialization to line 41

2024-11-21 23:48 UTC, lunasrc commented on app/src/main/java/com/epfl/beatlink/repository/profile/ProfileRepositoryFirestore.kt
> +              profilePicture = profilePicture,
```suggestion
              profilePicture = snapshot.getString("profilePicture"),
```

2024-11-21 23:48 UTC, lunasrc commented on app/src/main/java/com/epfl/beatlink/viewmodel/profile/ProfileViewModel.kt
> +  // create factory
This comment can be deleted

2024-11-21 23:48 UTC, lunasrc commented on app/src/main/java/com/epfl/beatlink/ui/profile/EditProfile.kt
> +                              profilePicture = "",
I would suggest to put `null` instead so It clearly indicates the absence of a profile picture.
```suggestion
                              profilePicture = null,
```

2024-11-22 06:55 UTC, arthur-wolf submitted a review, later dismissed
Fantastic work on refactoring the profile picture handling! 🎉 Switching from Uri to Bitmap and Base64 encoding is a thoughtful move to improve performance and compatibility, especially with the updated methods for resizing, compressing, and converting images. The attention to detail in updating both the backend and UI components ensures seamless integration across the app.

I also appreciate how you’ve addressed every aspect of the profile feature, from the repository and model changes to the UI updates in ProfileScreen and EditProfileScreen. These improvements will undoubtedly make the profile picture handling more efficient and user-friendly.

The changes look clean and well-executed—approved! 🚀

2024-11-22 07:38 UTC, lunasrc approved these changes
The changes have been made, everything looks good to me ! Thank you for your great work.

2024-11-22 07:57 UTC, merged